### ISSUE TITLE
h5模式下运行会报错(mpvue-packager和ithome-lite都是同一个错误)

### ISSUE THREAD

**Issue by doinbean** [F-loat/ithome-lite#32]
(node:3652) UnhandledPromiseRejectionWarning: TypeError: Cannot destructure property `compile` of 'undefined' or 'null'.
    at addHooks (/Users/yuchen/Documents/demo/ithome-lite/node_modules/webpack-dev-server/lib/Server.js:131:49)
    at new Server (/Users/yuchen/Documents/demo/ithome-lite/node_modules/webpack-dev-server/lib/Server.js:144:5)
    at module.exports.require.then.webpackConfig (/Users/yuchen/Documents/demo/ithome-lite/node_modules/mpvue-packager-h5-plugin/dev.js:18:18)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
    at Function.Module.runMain (module.js:703:11)
    at startup (bootstrap_node.js:190:16)
    at bootstrap_node.js:662:3
(node:3652) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:3652) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by F-loat** [comment]
删除 lock 文件后重新安装下依赖，新版不兼容

**Comment by mizhiming521** [comment]
package-lock.json 文件之后  npm install 之后 npm run dev:h5 还是报错

**Comment by F-loat** [comment]
@mizhiming521 最近一个版本的 mpvue-loader 有点兼容问题，他们修复了应该

**Comment by F-loat** [comment]
@mizhiming521 h5 有问题？具体是什么报错
